server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false   #请修改成自己的
    username: root  #请修改成自己的
    password:  #请修改成自己的
    druid:
      test-while-idle: false #关闭ali池的一个sql连接测试,如果用1.1.20以上版本就不用加

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.vbaicai.springcloud.entity  #请修改成自己的
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka